---
include:
- "**/*.rb"
# exclude:
# - spec/**/*
# - test/**/*
# - vendor/**/*
# - ".bundle/**/*"
domains: []
reporters:
- rubocop
- require_not_found
require_paths: []
max_files: 5000
require:
- actioncable
- actionmailer
- actionpack
- actionview
- activejob
- activemodel
- activerecord
- activestorage
- activesupport

