version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-buster-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello World"
