::::::::::::::
docker-compose.yml
::::::::::::::
version: '3.3'

services:
  meilisearch:
    image: getmeili/meilisearch:${MEILI_TAG}
    restart: always
    container_name: vdp_meilisearch
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ENV: production
      MEILI_NO_ANALYTICS: true
    ports:
      - '127.0.0.1:7700:7700'
      # Where our data will be persisted
    volumes:
      - ${MEILI_DATA_PATH}:/meili_data
