version: '3.3'
services:
  db:
    image: mysql:8.0
    container_name: vdp_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - vdp-mysql-db:/var/lib/mysql

  redis:
    image: "redis:5-alpine"
    container_name: vdp_redis
    ports:
      - 6379:6379
    volumes:
      - vdp-redis-db:/data

  meilisearch:
    image: getmeili/meilisearch:${MEILI_TAG}
    container_name: vdp_meilisearch
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ENV: production
      MEILI_NO_ANALYTICS: true
    ports:
      - '7700:7700'
      # Where our data will be persisted
    volumes:
      - ${MEILI_DATA_PATH}:/meili_data

# Names our volume
volumes:
  vdp-mysql-db:
  vdp-redis-db:
