common: &common
  audios_root: "/Users/jschwindt/Projects/venganzas_del_pasado"
  audios_folders:
    - /st0/
    - /st1/
    - /st2/
    - /st3/

development:
  <<: *common
  find_show_start: "/Users/jschwindt/Projects/whisper/.venv/bin/python /Users/jschwindt/Projects/whisper/find_show_start.py"
  audios_root: "/Users/jschwindt/Projects/venganzas_del_pasado"

test:
  <<: *common

production:
  <<: *common
  find_show_start: "/home/jschwindt/whisper/.venv/bin/python /home/jschwindt/whisper/find_show_start.py"
  audios_root: "/var/www/venganzasdelpasado.com.ar"
