common: &common
  audios_folders:
    - /st0/
    - /st1/
    - /st2/
    - /st3/

development:
  <<: *common
  speech_to_text_cmd: "source /Users/jschwindt/Projects/vdp-vosk/.env-local; /Users/jschwindt/Projects/vdp-vosk/.venv/bin/python /Users/jschwindt/Projects/vdp-vosk/process_stt.py -m /Users/jschwindt/Projects/vdp-vosk/model > /tmp/last_stt.log 2>&1"
  audios_root: "/Users/jschwindt/Projects/venganzas_del_pasado"

test:
  <<: *common

production:
  <<: *common
  speech_to_text_cmd: "source /home/jschwindt/vosk/.env; /home/jschwindt/vosk/.venv/bin/python /home/jschwindt/vosk/process_stt.py -m /home/jschwindt/vosk/model > /tmp/last_stt.log 2>&1"
  audios_root: "/var/www/venganzasdelpasado.com.ar"
